application: webpy-jinja2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: webapp2-jinja2.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
